[build]
  publish = "public/"

[build.environment]
  HUGO_VERSION = "0.130.0"

[context.production]
  command = "hugo"

[context.deploy-preview]
  command = "hugo --buildDrafts -e preview -b $DEPLOY_PRIME_URL"
